/*
SELECT * FROM MEMBER;
SELECT * FROM SCHOOL;
SELECT * FROM SCHOOLING;
SELECT * FROM DEGREE_INFO;
SELECT * FROM HIGHER_EDUCATION;
SELECT * FROM SKILLS;
SELECT * FROM PROJECTS;
SELECT * FROM JOB;
SELECT * FROM EXPERIENCE;
SELECT * FROM ACCOMPLISHMENTS;
SELECT * FROM CERTIFICATIONS;
*/

/*
INSERT INTO MEMBER VALUES('MEM#000004', 'atmik123', 'Atmik Ajoy', 'atmikajoy@gmail.com', '9327891567', 'BDA Complex', 'Always ready for challenges.', 'www.atmik.github.com', 'www.atmik.linkedin.com');
INSERT INTO SCHOOL VALUES('SCH#000005', 'Banashankari', 'LFPS');
INSERT INTO SCHOOL VALUES('SCH#000006', 'Banashankari', 'Ammatra Academy');
INSERT INTO SCHOOLING VALUES('MEM#000004', 'SCH#000005', 10, 'Science', 2016, '90');
INSERT INTO SCHOOLING VALUES('MEM#000004', 'SCH#000006', 12, 'Science', 2018, '90');
INSERT INTO DEGREE_INFO VALUES('DEG#000001', 'Bachelor''s', 'B.Tech', 'Computer Science');
INSERT INTO HIGHER_EDUCATION VALUES('MEM#000004', 'DEG#000001', 8.1, 'PES University');
INSERT INTO SKILLS VALUES('MEM#000004', 'Machine Learning', 8);
INSERT INTO PROJECTS VALUES('MEM#000004', 'Reccomender engine for movies', 'Built a recommendation engine');
INSERT INTO JOB VALUES('JOB#000004', 'SME', 'Bangalore', 'SME for Reccomender engines', 'PESU IO');
INSERT INTO EXPERIENCE VALUES('MEM#000004', 'JOB#000004', '2019-08-20', '2019-10-12', 0);
INSERT INTO ACCOMPLISHMENTS VALUES('MEM#000004', 'Microsoft student partner', 'MSP for PESU');
INSERT INTO CERTIFICATIONS VALUES ('MEM#000004', 'coursera/RE/20190716', 'Reccomender engines');
*/

/*
DELETE FROM MEMBER;
DELETE FROM SCHOOL;
DELETE FROM SCHOOLING;
DELETE FROM DEGREE_INFO;
DELETE FROM HIGHER_EDUCATION;
DELETE FROM SKILLS;
DELETE FROM PROJECTS;
DELETE FROM JOB;
DELETE FROM EXPERIENCE;
DELETE FROM ACCOMPLISHMENTS;
DELETE FROM CERTIFICATIONS;
*/
